'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms. 

answer: 4613732
'''

def fib(n, dict={}):
    if n in dict:
        return dict[n]
    if n <= 2:
        return n
    rtn = fib(n - 1, dict) + fib(n - 2, dict)
    dict[n] = rtn
    return rtn

sum = 0
term = 2

while True:
    tmp = fib(term)
    if tmp >= 4000000: break
    if tmp % 2 == 0:
        sum += tmp
    term += 3 # the (2+3n)th term is even for n = 0, 1, 2, ...
    
print(sum)