'''
Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5. 

If they are then placed in numerical order, with any repeats removed, we get the following
sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125.

How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?

answer: 9183
'''

def disPowSeq(size):
    rtn = []
    for i in range(2, size + 1):
        for j in range(2, size + 1):
            tmp = i ** j
            if tmp not in rtn:
                rtn.append(tmp)
    rtn.sort()
    return rtn

if __name__ == '__main__':
    seq = disPowSeq(100)
    print(len(seq))